### ISSUE TITLE
GoogleJsonResponseException: Your project does not have access to this feature.,

### ISSUE THREAD

**Issue by iulianabaciu** [rmeekers/Google-Analytics-Manager#38]
I get this issue for some other website I am managing (from other company) .. I've tested your Google docs sheet and when I want to Insert / to Google Analytics > i get this issue >>

GoogleJsonResponseException: Your project does not have access to this feature.,

**Comment by rmeekers** [comment]
@iulianabaciu please see http://rutger.meekers.eu/Google-Analytics-Manager/#limitations for mor information.
