### ISSUE TITLE
Error on audit

### ISSUE THREAD

**Issue by rmeekers** [rmeekers/Google-Analytics-Manager#39]
On auditing this error pops up:
<img width="409" alt="error cwp google analytics - rutger procurios eu - procurios mail 2017-08-17 15-42-45" src="https://user-images.githubusercontent.com/5755308/29415272-d06ec8e2-8362-11e7-833f-be9c4c90da11.png">

Probably the city list needs an update.
Reported by @iulianabaciu

**Comment by iulianabaciu** [comment]
ok., the test was for another company.. but the audit works for the company we work for at this moment..  :P
